# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: é˜³å…‰å°é¥ºå­çš„ç©ºé—´
subtitle: å°æ´‹åšå®¢-Ysnsn
description: å°æ´‹çš„å°çª
keywords: Ysnsn | å°æ´‹åšå®¢ | ç”Ÿæ´»éšè®° | é˜³å…‰å°é¥ºå­
author: å¯çˆ±çš„Wyang
language: zh-CN
timezone: Asia/shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://ysnsn.cn
root: /
permalink: :abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
	- index.html
	- qq/**
	- mikutap/**
	- djs/**
	- zhuye/**
	- music/**
	- xc/**
	- love/**
	- dujitang/**
	- plane/**
	- saolei/**
	- caidie/**
	- lxw/**
	- å¹æ³¡æ³¡/**
	- æ–¹å—ç©¿æ¢­/**
	- é²¨é±¼/**
	- æ·±æµ·æ°´æ¯/**
	- æ¶²ä½“/**
	- fireworks/**
	- spjx/**
	- wysp/**
	- sjz/**
	- aiqiyi/**
	- sc/**
	- smail/**
	- time/**
	- bangumis/**
	- silk/**

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 9
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 9
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly1

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: https://github.com/Ysnsn/Ysnsn.github.io.git # å°†usernameä¿®æ”¹æˆä½ çš„Githubç”¨æˆ·å   ## coding: https://e.coding.net/ysnsn/blog/Ysnsn.git
  branch: master
  ignore_hidden: false  # å¿½ç•¥éšè—æ–‡ä»¶åŠæ–‡ä»¶å¤¹(ç›®å½•)

# RSSè®¢é˜…æ”¯æŒ
plugin:
- hexo-generator-feed

# Feed Atom
feed:
type: atom
path: atom.xml
limit: 20

abbrlink: 
    alg: crc16 #ç®—æ³•ï¼š 
    crc16(default) and crc32 rep: hex #è¿›åˆ¶ï¼š dec(default) and hex: dec #è¾“å‡ºè¿›åˆ¶ï¼šåè¿›åˆ¶å’Œåå…­è¿›åˆ¶ï¼Œé»˜è®¤ä¸º10è¿›åˆ¶ã€‚ä¸¨decä¸ºåè¿›åˆ¶ï¼Œhexä¸ºåå…­è¿›åˆ¶
    

bangumi:
  enable: true
  path: bangumis/index.html
  vmid: 483622363
  title: 'è¿½ç•ªåˆ—è¡¨ğŸ‘€'
  quote: 'ç”Ÿå‘½ä¸æ¯ï¼Œè¿½ç•ªä¸æ­¢ï¼ğŸ›´'
  show: 1
  loading:
  metaColor:
  color: "#ffc0cb"
  webp:
  progress: true
  

live2d:
  enable: true # å¼€å¯live2d
  # enable: false
  scriptFrom: local # é»˜è®¤
  pluginRootPath: live2d/ # æ’ä»¶åœ¨ç«™ç‚¹ä¸Šçš„æ ¹ç›®å½•(ç›¸å¯¹è·¯å¾„)
  pluginJsPath: lib/ # è„šæœ¬æ–‡ä»¶ç›¸å¯¹ä¸æ’ä»¶æ ¹ç›®å½•è·¯å¾„
  pluginModelPath: assets/ # æ¨¡å‹æ–‡ä»¶ç›¸å¯¹ä¸æ’ä»¶æ ¹ç›®å½•è·¯å¾„
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # ä½ çš„è‡ªå®šä¹‰ url
  tagMode: false # æ ‡ç­¾æ¨¡å¼, æ˜¯å¦ä»…æ›¿æ¢ live2d tagæ ‡ç­¾è€Œéæ’å…¥åˆ°æ‰€æœ‰é¡µé¢ä¸­
  debug: false # è°ƒè¯•, æ˜¯å¦åœ¨æ§åˆ¶å°è¾“å‡ºæ—¥å¿—
  display:
     position: left
  mobile:
     show: false   
  model:
     scale: 1.2
     use: weier


# è°·æ­Œã€ç™¾åº¦ç«™ç‚¹åœ°å›¾ç”Ÿæˆ
Plugins:
- hexo-generator-baidu-sitemap
- hexo-generator-sitemap

baidusitemap:
    path: baidusitemap.xml
sitemap:
    path: sitemap.xml